namespace: hello-kubernetes
docker:
  registry: ghcr.io/jotheesh-joe
  image:
    name: hello-kubernetes
    version: 2cba74916d4cd7657fdf50ba9c7a0c86d7977219
  container:
    targetPort: 80
service:
  port: 8000
  protocol: http
deployment:
  replicas: 1
resources:
  requests:
    cpu: 200m
    memory: 4Gi
  limits:
    cpu: 2000m
    memory: 16Gi
istio:
  config:
    domain: hello-kubernetes.jotheesh-joe.com
    tls:
      enabled: true
      mode: simple
      secret: hello-kubernetes-secret
