name: hello-kubernetes github action
on:
  push:
    paths:
      - app/**
jobs:
  publish-hello-kubernetes-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Hello Kubernetes Docker image
        run: |
          IMAGE_TAG="ghcr.io/jotheesh-joe/hello-kubernetes:${{ github.sha }}"
          docker build . -f app/Dockerfile --tag $IMAGE_TAG
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'ghcr.io/jotheesh-joe/hello-kubernetes:${{ github.sha }}'
          format: 'json'
          output: 'trivy-report.json'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-report.json
      - name: Push the Docker image
        run: |
          IMAGE_TAG="ghcr.io/jotheesh-joe/hello-kubernetes:${{ github.sha }}"
          docker push $IMAGE_TAG
  
  
  update-hellokubernetes-helmchart:
    needs: [publish-hello-kubernetes-image]
    if: ${{ always() && !cancelled() && needs.publish-hello-kubernetes-image.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Update docker image version in values yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: true
          branch: main
          createPR: false
          message: "hello-kubernetes helm chart docker version updated"  
          changes: |
            {
              "helm/hello-kubernetes/values.yaml": {
                "docker.image.version": "${{ github.sha }}"
              },
              "helm/hello-kubernetes/Chart.yaml": {
                "version": "0.${{ github.run_number }}"
              }
            }
          
        
